---
deployment:
  tasks:
    - export DEPLOYPATH=/home/onlw4213/public_html/
    - /bin/cp -r * $DEPLOYPATH
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan optimize:clear
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan config:clear
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan cache:clear
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan route:clear
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan view:clear
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan config:cache
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan route:cache
    - /usr/local/bin/php /home/onlw4213/public_html/php artisan view:cache
