[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "php82Extensions.swoole",
    "nodejs_20"
]

[phases.install]
cmds = [
    "composer install --no-dev",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan package:discover --ansi",
    "php artisan storage:link || true",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan optimize"
]

[start]
cmd = "bash start.sh"

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "20"
APP_ENV = "production"
APP_DEBUG = "false"
