[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "nodejs_20"
]

[phases.install]
cmds = [
    "composer install --no-dev",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan package:discover --ansi",
    "php artisan storage:link || true",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan optimize"
]

[start]
cmd = "bash start.sh"

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "20"
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:your-app-key-here"
APP_URL = "https://your-domain.com"
DB_CONNECTION = "mysql"
DB_HOST = "db"
DB_PORT = "3306"
DB_DATABASE = "onlymainails"
DB_USERNAME = "ateng"
DB_PASSWORD = "!Sesaknapas98"
MAIL_MAILER = "smtp"
MAIL_HOST = "smtp.gmail.com"
MAIL_PORT = "587"
MAIL_USERNAME = ""
MAIL_PASSWORD = ""
MAIL_ENCRYPTION = "tls"
MAIL_FROM_ADDRESS = "noreply@onlymainails.com"
MAIL_FROM_NAME = "OnlyMaiNails"
