[phases.setup]
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "php83Extensions.bcmath",
    "php83Extensions.ctype",
    "php83Extensions.curl",
    "php83Extensions.dom",
    "php83Extensions.fileinfo",
    "php83Extensions.filter",
    "php83Extensions.gd",
    "php83Extensions.hash",
    "php83Extensions.iconv",
    "php83Extensions.intl",
    "php83Extensions.json",
    "php83Extensions.mbstring",
    "php83Extensions.openssl",
    "php83Extensions.pcre",
    "php83Extensions.pdo",
    "php83Extensions.pdo_mysql",
    "php83Extensions.pdo_sqlite",
    "php83Extensions.session",
    "php83Extensions.simplexml",
    "php83Extensions.tokenizer",
    "php83Extensions.xml",
    "php83Extensions.xmlreader",
    "php83Extensions.xmlwriter",
    "php83Extensions.zip",
    "php83Extensions.zlib",
    "imagemagick",
    "nodejs_20"
]

[phases.install]
cmds = [
    "composer config --global process-timeout 2000",
    "composer config --global memory-limit -1",
    "composer install --optimize-autoloader --no-interaction --prefer-dist --no-dev",
    "npm ci --prefer-offline --no-audit",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan package:discover --ansi",
    "php artisan storage:link || true",
    "php artisan optimize"
]

[start]
cmd = "./start.sh"

[variables]
PHP_VERSION = "8.3"
NODE_VERSION = "20"
APP_ENV = "production"
APP_DEBUG = "false"
FORCE_HTTPS = "true"
SESSION_SECURE_COOKIE = "true"
COMPOSER_MEMORY_LIMIT = "-1"
COMPOSER_PROCESS_TIMEOUT = "2000"
