[phases.setup]
nixPkgs = [
    "php83",
    "php83Packages.composer",
    "nodejs_20"
]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-interaction",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan package:discover --ansi",
    "php artisan storage:link || true",
    "php artisan optimize",
    "chmod +x start.sh"
]

[start]
cmd = "bash start.sh"

[variables]
PHP_VERSION = "8.3"
NODE_VERSION = "20"
DB_CONNECTION = "mysql"
DB_HOST = "db"
DB_PORT = "3306"
DB_DATABASE = "onlymainails"
DB_USERNAME = "ateng"
DB_PASSWORD = "!Sesaknapas98"
